using System.Text.Json;
using Microsoft.Graphics.Canvas;

namespace FalloutXbox360Utils;

/// <summary>
///     Loads and caches pre-rendered NIF sprites for the world map viewer.
///     Sprites are loaded from a directory generated by the <c>render nif</c> CLI command.
/// </summary>
internal sealed class WorldMapSpriteRegistry : IDisposable
{
    private readonly Dictionary<string, SpriteEntry> _sprites = new(StringComparer.OrdinalIgnoreCase);
    private bool _disposed;

    public int Count => _sprites.Count;

    /// <summary>
    ///     Load sprites from a directory containing sprite-index.json and PNG files.
    /// </summary>
    public static WorldMapSpriteRegistry? Load(string spriteDir, ICanvasResourceCreator resourceCreator)
    {
        var indexPath = Path.Combine(spriteDir, "sprite-index.json");
        if (!File.Exists(indexPath))
        {
            return null;
        }

        var json = File.ReadAllText(indexPath);
        var indexData = JsonSerializer.Deserialize<Dictionary<string, SpriteIndexEntry>>(json);
        if (indexData == null || indexData.Count == 0)
        {
            return null;
        }

        var registry = new WorldMapSpriteRegistry();
        var loaded = 0;

        foreach (var (modelPath, entry) in indexData)
        {
            var pngPath = Path.Combine(spriteDir, entry.File);
            if (!File.Exists(pngPath))
            {
                continue;
            }

            try
            {
                using var stream = File.OpenRead(pngPath);
                var bitmap = CanvasBitmap.LoadAsync(resourceCreator, stream.AsRandomAccessStream())
                    .GetAwaiter().GetResult();

                registry._sprites[NormalizePath(modelPath)] = new SpriteEntry
                {
                    Bitmap = bitmap,
                    BoundsWidth = entry.BoundsWidth,
                    BoundsHeight = entry.BoundsHeight
                };
                loaded++;
            }
            catch
            {
                // Skip sprites that fail to load
            }
        }

        return loaded > 0 ? registry : null;
    }

    /// <summary>
    ///     Look up a sprite by model path (e.g., "meshes\architecture\goodsprings\gsgate01.nif").
    /// </summary>
    public SpriteEntry? GetSprite(string? modelPath)
    {
        if (modelPath == null)
        {
            return null;
        }

        return _sprites.GetValueOrDefault(NormalizePath(modelPath));
    }

    private static string NormalizePath(string path)
    {
        return path.Replace('/', '\\').ToLowerInvariant();
    }

    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;
        foreach (var entry in _sprites.Values)
        {
            entry.Bitmap.Dispose();
        }

        _sprites.Clear();
    }

    internal sealed class SpriteEntry
    {
        public required CanvasBitmap Bitmap { get; init; }
        public required float BoundsWidth { get; init; }
        public required float BoundsHeight { get; init; }
    }

    private sealed class SpriteIndexEntry
    {
        public string File { get; set; } = "";
        public float BoundsWidth { get; set; }
        public float BoundsHeight { get; set; }
    }
}
