using FalloutXbox360Utils.Core;
using FalloutXbox360Utils.Core.Formats;
using Xunit;

namespace FalloutXbox360Utils.Tests.Core.Formats;

/// <summary>
///     Tests for file type color coding.
///     Verifies that each format has the correct category and color assignment.
///     Colors are dynamically generated by FormatRegistry (single source of truth).
/// </summary>
public class FileColoringTests
{
    #region Format Category Tests

    [Theory]
    [InlineData("xui", FileCategory.Xbox)]
    [InlineData("xdbf", FileCategory.Xbox)]
    [InlineData("dds", FileCategory.Texture)]
    [InlineData("ddx", FileCategory.Texture)]
    [InlineData("png", FileCategory.Image)]
    [InlineData("xma", FileCategory.Audio)]
    [InlineData("lip", FileCategory.Audio)]
    [InlineData("nif", FileCategory.Model)]
    public void Format_HasCorrectCategory(string formatId, FileCategory expectedCategory)
    {
        var format = FormatRegistry.GetByFormatId(formatId);

        Assert.NotNull(format);
        Assert.Equal(expectedCategory, format.Category);
    }

    [Theory]
    [InlineData("xui_scene", FileCategory.Xbox)]
    [InlineData("xui_binary", FileCategory.Xbox)]
    [InlineData("xdbf", FileCategory.Xbox)]
    [InlineData("dds", FileCategory.Texture)]
    [InlineData("ddx_3xdo", FileCategory.Texture)]
    [InlineData("ddx_3xdr", FileCategory.Texture)]
    [InlineData("png", FileCategory.Image)]
    [InlineData("xma", FileCategory.Audio)]
    [InlineData("lip", FileCategory.Audio)]
    [InlineData("nif", FileCategory.Model)]
    public void SignatureId_ResolvesToCorrectCategory(string signatureId, FileCategory expectedCategory)
    {
        var category = FormatRegistry.GetCategory(signatureId);

        Assert.Equal(expectedCategory, category);
    }

    #endregion

    #region Category Color Tests

    [Fact]
    public void CategoryColors_ContainsAllCategories()
    {
        var allCategories = Enum.GetValues<FileCategory>();

        foreach (var category in allCategories)
        {
            Assert.True(FormatRegistry.CategoryColors.ContainsKey(category),
                $"Category {category} should have a color defined");
        }
    }

    [Fact]
    public void CategoryColors_AllDynamicColorsAreDistinct()
    {
        var dynamicColors = FormatRegistry.CategoryColors
            .Where(kvp => kvp.Key != FileCategory.Header)
            .Select(kvp => kvp.Value)
            .ToList();

        var distinctCount = dynamicColors.Distinct().Count();

        Assert.Equal(dynamicColors.Count, distinctCount);
    }

    [Fact]
    public void CategoryColors_HeaderIsHardcodedSteelGray()
    {
        Assert.Equal(0xFF708090u, FormatRegistry.CategoryColors[FileCategory.Header]);
    }

    #endregion

    #region CarvedFileInfo Color Assignment Tests

    [Theory]
    [InlineData(FileCategory.Xbox)]
    [InlineData(FileCategory.Module)]
    [InlineData(FileCategory.Image)]
    [InlineData(FileCategory.Texture)]
    [InlineData(FileCategory.Audio)]
    [InlineData(FileCategory.Model)]
    [InlineData(FileCategory.Script)]
    [InlineData(FileCategory.Header)]
    [InlineData(FileCategory.EsmData)]
    public void CarvedFileInfo_WithCategory_GetsExpectedColor(FileCategory category)
    {
        var file = new CarvedFileInfo
        {
            Offset = 0x1000,
            Length = 0x100,
            FileType = "Test File",
            Category = category
        };

        var actualColor = FormatRegistry.CategoryColors.GetValueOrDefault(file.Category, FormatRegistry.UnknownColor);

        Assert.Equal(FormatRegistry.CategoryColors[category], actualColor);
    }

    [Fact]
    public void CarvedFileInfo_ModuleCategory_HasColor()
    {
        var dllFile = new CarvedFileInfo
        {
            Offset = 0x0CB176E4,
            Length = 100000,
            FileType = "Xbox 360 Module (DLL)",
            FileName = "test.dll",
            SignatureId = "module",
            Category = FileCategory.Module
        };

        Assert.True(FormatRegistry.CategoryColors.TryGetValue(dllFile.Category, out _),
            "Module category should have a color");
    }

    [Fact]
    public void CarvedFileInfo_XuiCategory_HasColor()
    {
        var xuiFile = new CarvedFileInfo
        {
            Offset = 0x0CB07B22,
            Length = 5000,
            FileType = "XUI Scene",
            SignatureId = "xui_scene",
            Category = FileCategory.Xbox
        };

        Assert.True(FormatRegistry.CategoryColors.TryGetValue(xuiFile.Category, out _),
            "Xbox category should have a color");
    }

    [Fact]
    public void CarvedFileInfo_XdbfCategory_NotSameAsImage()
    {
        var xboxColor = FormatRegistry.CategoryColors[FileCategory.Xbox];
        var imageColor = FormatRegistry.CategoryColors[FileCategory.Image];

        Assert.NotEqual(imageColor, xboxColor);
    }

    #endregion

    #region GetColor by SignatureId Tests

    [Theory]
    [InlineData("xui_scene", FileCategory.Xbox)]
    [InlineData("xui_binary", FileCategory.Xbox)]
    [InlineData("xdbf", FileCategory.Xbox)]
    [InlineData("dds", FileCategory.Texture)]
    [InlineData("ddx_3xdo", FileCategory.Texture)]
    [InlineData("png", FileCategory.Image)]
    [InlineData("xma", FileCategory.Audio)]
    [InlineData("nif", FileCategory.Model)]
    public void GetColor_BySignatureId_ReturnsExpectedCategoryColor(string signatureId, FileCategory expectedCategory)
    {
        var actualColor = FormatRegistry.GetColor(signatureId);
        var expectedColor = FormatRegistry.CategoryColors[expectedCategory];

        Assert.Equal(expectedColor, actualColor);
    }

    [Fact]
    public void GetColor_MinidumpHeader_ReturnsHeaderColor()
    {
        var category = FormatRegistry.GetCategory("minidump_header");
        var actualColor = FormatRegistry.CategoryColors.GetValueOrDefault(category, FormatRegistry.UnknownColor);

        Assert.Equal(FormatRegistry.CategoryColors[FileCategory.Header], actualColor);
    }

    #endregion

    #region Real World Scenario Tests

    [Fact]
    public void RealWorld_XuiSceneAtOffset_ShouldBeXboxCategory()
    {
        var xuiFile = new CarvedFileInfo
        {
            Offset = 0x0CB07B22,
            Length = 5000,
            FileType = "XUI Scene",
            SignatureId = "xui_scene",
            Category = FileCategory.Xbox
        };

        Assert.Equal(FileCategory.Xbox, xuiFile.Category);
        Assert.True(FormatRegistry.CategoryColors.ContainsKey(xuiFile.Category));
    }

    [Fact]
    public void RealWorld_DllAtOffset_ShouldBeModuleCategory()
    {
        var dllFile = new CarvedFileInfo
        {
            Offset = 0x0CB176E4,
            Length = 655360,
            FileType = "Xbox 360 Module (DLL)",
            FileName = "xbdm.dll",
            SignatureId = "module",
            Category = FileCategory.Module
        };

        Assert.Equal(FileCategory.Module, dllFile.Category);
        Assert.True(FormatRegistry.CategoryColors.ContainsKey(dllFile.Category));
    }

    [Fact]
    public void RealWorld_XurAtOffset_ShouldBeXboxCategory()
    {
        var xurFile = new CarvedFileInfo
        {
            Offset = 0x0CA5B8AA,
            Length = 2000,
            FileType = "XUI Binary",
            SignatureId = "xui_binary",
            Category = FileCategory.Xbox
        };

        Assert.Equal(FileCategory.Xbox, xurFile.Category);
        Assert.True(FormatRegistry.CategoryColors.ContainsKey(xurFile.Category));
    }

    [Theory]
    [InlineData(0x0A191384)]
    [InlineData(0x0A193384)]
    public void RealWorld_XdbfAtOffset_ShouldBeXboxCategory_NotImage(long offset)
    {
        var xdbfFile = new CarvedFileInfo
        {
            Offset = offset,
            Length = 10000,
            FileType = "Xbox Dashboard File",
            SignatureId = "xdbf",
            Category = FileCategory.Xbox
        };

        Assert.Equal(FileCategory.Xbox, xdbfFile.Category);
        var xboxColor = FormatRegistry.CategoryColors[xdbfFile.Category];
        var imageColor = FormatRegistry.CategoryColors[FileCategory.Image];
        Assert.NotEqual(imageColor, xboxColor);
    }

    [Theory]
    [InlineData("xdbf", FileCategory.Xbox)]
    [InlineData("xui_scene", FileCategory.Xbox)]
    [InlineData("xui_binary", FileCategory.Xbox)]
    [InlineData("png", FileCategory.Image)]
    [InlineData("dds", FileCategory.Texture)]
    [InlineData("ddx_3xdo", FileCategory.Texture)]
    [InlineData("xma", FileCategory.Audio)]
    [InlineData("nif", FileCategory.Model)]
    public void GetBySignatureId_ReturnsFormatWithCorrectCategory(string signatureId, FileCategory expectedCategory)
    {
        var format = FormatRegistry.GetBySignatureId(signatureId);

        Assert.NotNull(format);
        Assert.Equal(expectedCategory, format.Category);
    }

    #endregion
}
