namespace FalloutXbox360Utils.Core.Formats.Esm.Plugin.AssetPacking;

/// <summary>
///     One emitted dialogue voice line, keyed by the triple the FNV engine uses at runtime
///     to construct voice-file lookup paths: <c>(VoiceTypeEditorId, ParentDialEditorId,
///     ResponseNumber)</c>. The same triple appears in the Fallout Audio Transcriber CSV
///     file paths, which lets the asset packer rewrite voice-file pack paths even when CSV
///     FormIDs come from a different build-era than the converter's source DMP.
///     <para>
///     Quest EDID and response text are recorded too so the collector can (1) construct the
///     engine-expected filename from scratch when source-CSV truncation differs from what
///     the runtime engine produces, and (2) disambiguate between multiple candidates that
///     share a topic-EDID prefix bucket.
///     </para>
/// </summary>
public sealed record EmittedDialogueAudioBinding
{
    /// <summary>The PC-plugin FormID our allocator issued for this INFO.</summary>
    public required uint AllocatedInfoFormId { get; init; }

    /// <summary>EditorID of the parent DIAL (master override or newly allocated).</summary>
    public required string ParentDialEditorId { get; init; }

    /// <summary>
    ///     EditorID of the speaker NPC's VoiceType (VTYP record). Null when the speaker has
    ///     no voice type resolved (engine falls back to default), which means no per-INFO
    ///     audio path is constructed — those bindings still feed the FormID-first match but
    ///     skip the triple-key fallback.
    /// </summary>
    public string? VoiceTypeEditorId { get; init; }

    /// <summary>1-based response number within the INFO record (matches TRDT slot).</summary>
    public required byte ResponseNumber { get; init; }

    /// <summary>
    ///     EditorID of the QUEST that owns this INFO's parent DIAL (resolved via QSTI). The
    ///     engine embeds the quest's editor ID (truncated) as the first stem of the voice
    ///     filename, so the packer needs it to reconstruct the runtime path when the CSV's
    ///     filename was generated by an older engine with a different truncation rule.
    /// </summary>
    public string? QuestEditorId { get; init; }

    /// <summary>
    ///     Plain text of the response (NAM1). Used by the prefix-fallback path to disambiguate
    ///     between multiple INFOs that share the same (voice, topic-prefix, response) bucket —
    ///     the CSV row's Text column tells us which INFO this audio actually corresponds to.
    /// </summary>
    public string? ResponseText { get; init; }
}
