namespace FalloutXbox360Utils.Core.Formats.Esm.Plugin.AssetPacking;

/// <summary>
///     Builds the runtime voice-file path that the Fallout: New Vegas engine constructs from
///     a (plugin, voiceType, quest, topic, INFO FormID, response) tuple. The packer uses this
///     to lay down audio bytes at the path the engine will actually open at runtime — which
///     differs from CSV-encoded paths when the source CSV was generated by an older engine
///     with a different filename truncation policy.
/// </summary>
/// <remarks>
///     <para>
///     Filename shape: <c>sound\voice\&lt;esp&gt;\&lt;voicetype&gt;\&lt;quest&gt;_&lt;topic&gt;_&lt;fid24:8x&gt;_&lt;resp&gt;.&lt;ext&gt;</c>.
///     </para>
///     <para>
///     Truncation rule (derived empirically from FNV PC final's runtime errors): the combined
///     <c>quest + "_" + topic</c> stem is capped at <see cref="MaxStemTotal"/> characters
///     (26). Topic is capped first at <see cref="MaxTopicStem"/> (15); quest takes whatever
///     remains. Vanilla examples fit naturally (e.g. <c>radionewvegas_rnvnewsintro</c> = 26).
///     The Ulysses error log confirms the policy: <c>VDialogueU_VDialogueUlysse</c> (10+15 = 26)
///     for a quest+topic that would otherwise be 16+31 = 48. Older builds (e.g. July 2010 disk
///     dump) used a more generous 30-char policy (14+15 stems), which is why CSV paths from
///     those builds don't match what the runtime now constructs — the rewrite recomputes the
///     filename from scratch using the current 26-char rule rather than copying the CSV path.
///     </para>
/// </remarks>
internal static class EngineVoicePathBuilder
{
    /// <summary>Voice file path prefix the engine concatenates ahead of {esp}/{voicetype}/.</summary>
    public const string VoicePrefix = "sound\\voice\\";

    /// <summary>Maximum total stem length (quest + underscore + topic) in the filename.</summary>
    public const int MaxStemTotal = 26;

    /// <summary>Hard cap on topic stem length within the filename.</summary>
    public const int MaxTopicStem = 15;

    /// <summary>
    ///     Compute the engine-shaped voice-file path for a given (plugin, voiceType, quest,
    ///     topic, allocated INFO FormID, response, ext) tuple. All path/filename parts are
    ///     lowercased — BSAs lowercase entries even though the engine path lookups are case-
    ///     insensitive, so lowercasing keeps the resolver's identity-comparison happy.
    /// </summary>
    public static string Build(
        string outputEspFileName,
        string voiceTypeEditorId,
        string questEditorId,
        string topicEditorId,
        uint allocatedInfoFormId,
        byte responseNumber,
        string extensionWithDot)
    {
        var (questTrunc, topicTrunc) = TruncateStemsForEngine(questEditorId, topicEditorId);
        var fid24 = (allocatedInfoFormId & 0x00FFFFFFu).ToString("x8");

        var esp = outputEspFileName.ToLowerInvariant();
        var voice = voiceTypeEditorId.ToLowerInvariant();
        var stem = $"{questTrunc.ToLowerInvariant()}_{topicTrunc.ToLowerInvariant()}_{fid24}_{responseNumber}";
        var ext = extensionWithDot.ToLowerInvariant();

        return $"{VoicePrefix}{esp}\\{voice}\\{stem}{ext}";
    }

    /// <summary>
    ///     Apply the FNV 26-char total-stem truncation rule: topic gets up to 15 chars; quest
    ///     gets whatever remains (so a 31-char topic forces a 10-char quest). When both stems
    ///     are short (combined &lt;= 26), they pass through unchanged.
    /// </summary>
    public static (string QuestTrunc, string TopicTrunc) TruncateStemsForEngine(
        string questEditorId,
        string topicEditorId)
    {
        var topicTrunc = topicEditorId.Length > MaxTopicStem
            ? topicEditorId[..MaxTopicStem]
            : topicEditorId;

        var questBudget = MaxStemTotal - 1 - topicTrunc.Length;
        if (questBudget < 0)
        {
            questBudget = 0;
        }

        var questTrunc = questEditorId.Length > questBudget
            ? questEditorId[..questBudget]
            : questEditorId;

        return (questTrunc, topicTrunc);
    }
}
