namespace FalloutXbox360Utils.Core.Formats.Esm.Script;

/// <summary>
///     Script parameter types from PDB SCRIPT_PARAM_TYPE enum (type 0xBB3A, 71 values).
///     Determines how compiled parameter data is encoded in bytecode.
/// </summary>
public enum ScriptParamType
{
    Char = 0,
    Int = 1,
    Float = 2,
    InventoryObject = 3,
    ObjectRef = 4,
    ActorValue = 5,
    Actor = 6,
    SpellItem = 7,
    Axis = 8,
    Cell = 9,
    AnimGroup = 10,
    MagicItem = 11,
    Sound = 12,
    Topic = 13,
    Quest = 14,
    Race = 15,
    Class = 16,
    Faction = 17,
    Sex = 18,
    Global = 19,
    FurnitureOrFormList = 20,
    Object = 21,
    ScriptVar = 22,
    Stage = 23,
    MapMarker = 24,
    ActorBase = 25,
    ContainerRef = 26,
    World = 27,
    CrimeType = 28,
    Package = 29,
    CombatStyle = 30,
    MagicEffect = 31,
    FormType = 32,
    Weather = 33,
    Npc = 34,
    Owner = 35,
    ShaderEffect = 36,
    FormList = 37,
    MenuIcon = 38,
    Perk = 39,
    Note = 40,
    MiscStat = 41,
    ImageSpaceMod = 42,
    ImageSpace = 43,
    VatsValue = 44,
    VatsValueData = 45,
    VoiceType = 46,
    EncounterZone = 47,
    IdleForm = 48,
    Message = 49,
    InvObjectOrFormList = 50,
    Alignment = 51,
    EquipType = 52,
    ObjectOrFormList = 53,
    Music = 54,
    CritStage = 55,
    NpcOrLevChar = 56,
    CreaOrLevCrea = 57,
    LevChar = 58,
    LevCrea = 59,
    LevItem = 60,
    Form = 61,
    Reputation = 62,
    Casino = 63,
    CasinoChip = 64,
    Challenge = 65,
    CaravanMoney = 66,
    CaravanCard = 67,
    CaravanDeck = 68,
    Region = 69
}
